name: jvm-server

on: push

jobs:
  scalatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Check codestyle
        run: |
          mvn --no-transfer-progress spotless:check
        working-directory: tsumugi-server

      - name: Run tests
        run: |
          mvn --no-transfer-progress test
        working-directory: tsumugi-server
        
