name: jvm-server

on: push

jobs:
  scalatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: sbt

      - name: Set up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9

      - name: Check codestyle
        run: |
          sbt root/scalafmtCheckAll
        working-directory: tsumugi-server

      - name: Run tests
        run: |
          sbt root/test
        working-directory: tsumugi-server
        
